name: Contributors
on: workflow_dispatch
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: .github/CONTRIBUTORS.svg
          round: true
          count: 20
          includeBots: false
